USE fabook_db;
GO
DROP FULLTEXT INDEX ON book
go
DROP FULLTEXT INDEX ON BOOK_DETAIL
go
DROP FULLTEXT INDEX ON category
go
DROP FULLTEXT CATALOG book_catalog
go

GO
CREATE FULLTEXT CATALOG book_catalog WITH ACCENT_SENSITIVITY = OFF AS DEFAULT;  
GO

go
CREATE FULLTEXT INDEX ON BOOK (BOOK_NAME LANGUAGE 1066) KEY INDEX PK_BOOK ON book_catalog;
CREATE FULLTEXT INDEX ON BOOK_DETAIL (book_desc LANGUAGE 1066) KEY INDEX PK_BOOK_DETAIL ON book_catalog;
CREATE FULLTEXT INDEX ON category (cate_name LANGUAGE 1066) KEY INDEX PK_CATEGORY ON book_catalog;
go
